# Form implementation generated from reading ui file 'loganalyzer2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(912, 905)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BrowseFiles = QtWidgets.QPushButton(parent=Form)
        self.BrowseFiles.setObjectName("BrowseFiles")
        self.horizontalLayout_2.addWidget(self.BrowseFiles)
        self.ClusterData = QtWidgets.QPushButton(parent=Form)
        self.ClusterData.setObjectName("ClusterData")
        self.horizontalLayout_2.addWidget(self.ClusterData)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Distance_Cluster = QtWidgets.QSlider(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Distance_Cluster.sizePolicy().hasHeightForWidth())
        self.Distance_Cluster.setSizePolicy(sizePolicy)
        self.Distance_Cluster.setMinimum(10)
        self.Distance_Cluster.setMaximum(90)
        self.Distance_Cluster.setSingleStep(5)
        self.Distance_Cluster.setSliderPosition(10)
        self.Distance_Cluster.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Distance_Cluster.setObjectName("Distance_Cluster")
        self.verticalLayout.addWidget(self.Distance_Cluster)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.sliderValue = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.sliderValue.setFont(font)
        self.sliderValue.setObjectName("sliderValue")
        self.horizontalLayout_2.addWidget(self.sliderValue)
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.Search = QtWidgets.QPushButton(parent=Form)
        self.Search.setObjectName("Search")
        self.horizontalLayout_2.addWidget(self.Search)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(parent=Form)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.textEdit = QtWidgets.QTextEdit(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "A\'s Log Analyzer"))
        self.BrowseFiles.setText(_translate("Form", "Browse.."))
        self.ClusterData.setText(_translate("Form", "Cluster"))
        self.label.setText(_translate("Form", "Cluster Granularity (0.1 -0.9)"))
        self.sliderValue.setText(_translate("Form", "0.1"))
        self.Search.setText(_translate("Form", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
