# Form implementation generated from reading ui file 'loganalyzer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(912, 905)
        self.BrowseFiles = QtWidgets.QPushButton(parent=Form)
        self.BrowseFiles.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.BrowseFiles.setObjectName("BrowseFiles")
        self.ClusterData = QtWidgets.QPushButton(parent=Form)
        self.ClusterData.setGeometry(QtCore.QRect(150, 10, 111, 31))
        self.ClusterData.setObjectName("ClusterData")
        self.Search = QtWidgets.QPushButton(parent=Form)
        self.Search.setGeometry(QtCore.QRect(710, 10, 121, 31))
        self.Search.setObjectName("Search")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(500, 10, 201, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget = QtWidgets.QListWidget(parent=Form)
        self.listWidget.setGeometry(QtCore.QRect(10, 80, 256, 821))
        self.listWidget.setObjectName("listWidget")
        self.textEdit = QtWidgets.QTextEdit(parent=Form)
        self.textEdit.setGeometry(QtCore.QRect(270, 80, 631, 821))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.Distance_Cluster = QtWidgets.QSlider(parent=Form)
        self.Distance_Cluster.setGeometry(QtCore.QRect(280, 20, 160, 16))
        self.Distance_Cluster.setMinimum(10)
        self.Distance_Cluster.setMaximum(90)
        self.Distance_Cluster.setSingleStep(5)
        self.Distance_Cluster.setSliderPosition(10)
        self.Distance_Cluster.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Distance_Cluster.setObjectName("Distance_Cluster")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(280, 50, 161, 16))
        self.label.setObjectName("label")
        self.sliderValue = QtWidgets.QLabel(parent=Form)
        self.sliderValue.setGeometry(QtCore.QRect(450, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.sliderValue.setFont(font)
        self.sliderValue.setObjectName("sliderValue")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.BrowseFiles.setText(_translate("Form", "Browse.."))
        self.ClusterData.setText(_translate("Form", "Cluster"))
        self.Search.setText(_translate("Form", "Search"))
        self.label.setText(_translate("Form", "Cluster Granularity (0.1 -0.9)"))
        self.sliderValue.setText(_translate("Form", "0.1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
